### ISSUE TITLE
pass a bool type as a string to the o_tag function

### ISSUE THREAD

**Issue by Yoda-Canada** [Loran-l/txt-to-html-converter#7]
def o_tag(tag, space="", params_str=None, close_tag=False) have four arguments and the third argument is string, but the coding line 146 pass a bool type.
 >       Lines = ["<doctype html>",
  >               o_tag("html", 'lang="{}"'.format(lang), True),

**Comment by Loran-l** [comment]
Good find.
Fixed. Removed extra argument.
